import { useEffect, useState } from 'react'
import { Routes, Route, Link } from 'react-router-dom'

import Progress  from './components/Progress'
import Be        from './routes/Be'
import Play      from './routes/Play'
import Create    from './routes/Create'
import Connect   from './routes/Connect'
import Influence from './routes/Influence'

import Keter   from '/src/routes/Sefirot/Keter.tsx'
import Chokhma from '/src/routes/Sefirot/Chokhma.tsx'
import Bina    from '/src/routes/Sefirot/Bina.tsx'
import Chesed  from '/src/routes/Sefirot/Chesed.tsx'
import Gevurah from '/src/routes/Sefirot/Gevurah.tsx'
import Tiferet from '/src/routes/Sefirot/Tiferet.tsx'
import Netzach from '/src/routes/Sefirot/Netzach.tsx'
import Hod     from '/src/routes/Sefirot/Hod.tsx'
import Yesod   from '/src/routes/Sefirot/Yesod.tsx'
import Malkhut from '/src/routes/Sefirot/Malkhut.tsx'
import flows   from './config/flows.json'
import content from './config/content.json'
import rules   from './config/rules.json'
import { getProgress } from './state/progress'
