import { useEffect, useState } from 'react'
import { Routes, Route, Link } from 'react-router-dom'

import Progress  from './components/Progress'
import Be        from './routes/Be'
import Play      from './routes/Play'
import Create    from './routes/Create'
import Connect   from './routes/Connect'
import Influence from './routes/Influence'

import Keter     from './routes/Sefirot/Keter'
import Chokhma   from './routes/Sefirot/Chokhma'
import Bina      from './routes/Sefirot/Bina'
import Chesed    from './routes/Sefirot/Chesed'
import Gevurah   from './routes/Sefirot/Gevurah'
import Tiferet   from './routes/Sefirot/Tiferet'
import Netzach   from './routes/Sefirot/Netzach'
import Hod       from './routes/Sefirot/Hod'
import Yesod     from './routes/Sefirot/Yesod'
import Malkhut   from './routes/Sefirot/Malkhut'

import flows   from './config/flows.json'
import content from './config/content.json'
import rules   from './config/rules.json'
import { getProgress } from './state/progress'
